name: CI
on:
  pull_request: {}
  push:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node (se houver package.json)
      - if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - if: hashFiles('package.json') != ''
        run: npm ci && npm test --if-present

      # Python (se houver requirements.txt)
      - if: hashFiles('requirements.txt') != ''
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest -q || echo "Sem testes"

      # Valida Dockerfile (se existir)
      - if: hashFiles('Dockerfile') != ''
        run: docker build -t ci-test .
