name: Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Run tests
        run: npm test

      - name: Notify Discord (always)
        if: always()
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          STATUS: ${{ job.status }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          payload=$(jq -n --arg c ":rocket: **${{ github.repository }}** — Tests finalizados: **$STATUS**. Ver detalhes: $RUN_URL" '{content:$c}')
          curl -fsSL -H "Content-Type: application/json" -d "$payload" "$WEBHOOK"
